baseurl = "https://saveflipper.ca/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "pink"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = false
  showLastUpdated = false

[languages]
  [languages.en]
    title = "Save Flipper"
    subtitle = "Security research tools should be encouraged, not prohibited. Obscurity is not security."
    keywords = ""
    copyright = "©Creative Commons"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "SaveFlipper.ca"
      logoHomeLink = "/"

